sound_config = {
    "calm": "calm.mp3",
    "doma": "doma.mp3",
    "huh": "huh.mp3",
    "jong": "jong.mp3",
    "menu": "menu.mp3",
    "note": "note.mp3",
    "ones": "ones.mp3",
    "somedrums": "somedrums.mp3",
    "Something": "Something.mp3",
    "stomp": "stomp.mp3",
    "stomp2": "stomp2.mp3",
    "trittle": "trittle.mp3",
    "trooper": "trooper.mp3",
    "zins": "zins.mp3",
    "charge": "charge.mp3",
    "click": "click.mp3",
    "good": "good.mp3",
    "heal": "heal.mp3",
    "one": "one.mp3",
    "poison": "poison.mp3",
    "roll": "roll.mp3",
    "shatter": "shatter.mp3",
    "text": "text.mp3"
}
